
name: Continuos Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-test:
    name: Run on Chrome 99
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - name: Install cypress and verify
        run: |
            npm ci
            $(npm bin)/cypress verify
      
      - name: Run Cypress tests
        run: npm run cypress:runChromeHeadles
        continue-on-error: true
        
      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
  

    
      
      
